# Generated by Django 5.2.8 on 2025-12-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Optional profile picture', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Optional display name for posts', max_length=50),
        ),
    ]
