# Generated by Django 5.2.8 on 2025-12-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_post_is_hidden_comment_commentvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ai_categories',
            field=models.JSONField(blank=True, help_text='AI category scores', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='ai_flagged',
            field=models.BooleanField(default=False, help_text='Flagged by AI content moderation'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ai_severity_score',
            field=models.FloatField(blank=True, help_text='AI severity score (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='show_crisis_resources',
            field=models.BooleanField(default=False, help_text='Show mental health resources (self-harm detected)'),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_categories',
            field=models.JSONField(blank=True, help_text='AI category scores', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_flagged',
            field=models.BooleanField(default=False, help_text='Flagged by AI content moderation'),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_severity_score',
            field=models.FloatField(blank=True, help_text='AI severity score (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='show_crisis_resources',
            field=models.BooleanField(default=False, help_text='Show mental health resources (self-harm detected)'),
        ),
    ]
