# Generated by Django 5.2.8 on 2025-12-07 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_add_ai_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_flagged', '-created_at'], name='posting_pos_is_flag_6d619b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_flagged', '-ai_severity_score', '-created_at'], name='posting_pos_is_flag_97d039_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['ai_flagged'], name='posting_pos_ai_flag_053193_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['post', 'vote_type'], name='posting_vot_post_id_03851e_idx'),
        ),
    ]
