# Generated by Django 5.2.8 on 2025-12-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABTestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('variant', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('event_type', models.CharField(choices=[('view', 'View'), ('click', 'Click')], max_length=10)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
