# Generated by Django 5.2.8 on 2025-12-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abtestlog',
            name='event_type',
            field=models.CharField(choices=[('view', 'View'), ('click', 'Click')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='abtestlog',
            name='variant',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], db_index=True, max_length=1),
        ),
    ]
